diff --git a/Makefile b/Makefile
index 7d5f801eea..9d62ce671e 100644
--- a/Makefile
+++ b/Makefile
@@ -3,7 +3,7 @@
 VERSION = 2018
 PATCHLEVEL = 07
 SUBLEVEL =
-EXTRAVERSION =
+EXTRAVERSION = -laird
 NAME =
 
 # *DOCUMENTATION*
